---
###############################################################################
# Proxmox Handlers
###############################################################################
# Global proxmox handlers.

- name: 'Restart pveproxy'
  ansible.builtin.service:
    name:  'pveproxy'
    state: 'restarted'

- name: 'Update grub'
  ansible.builtin.command: 'update-grub'
  changed_when: false

- name: 'Reboot PVE'
  ansible.builtin.reboot:
