---
###############################################################################
# Cluster Node Firewall (host_vars)
###############################################################################
# Cluster node-specific firewall configuration. Specific host rules always
# override datacenter rules if there is a conflict. See Host Specific
# Configuration.
#
# Firewall files do not exist unless settings are explicitly set. Automatically
# generate a file with default settings to ensure consistency across following
# runs. Initial run will create a firewall definition for cluster node.
#
# pve-firewall service does not need to be restarted; it will automatically
# apply changes on file change.
#
# /etc/pve uses pmxcfs (a database mounted via fuse). It's POSIX like, but does
# not support specific operations. This causes:
# * Temp files from ansible to fail as it crosses filesystem boundaries
#   (ansible creates a temp file then attempts an atomic move; fails across
#    filesystems).
# * Permissions are auto-applied based on path; no need to set user/group/perms
#   on files in /etc/pve.
# * A Quorate MUST exist to enable writes (auto sync'ed to rest of cluster).
#
# Args:
#   host: string FQDN host from hosts 'pve_nodes'.
#
# Reference:
# * https://pve.proxmox.com/pve-docs/chapter-pve-firewall.html#pve_firewall_host_specific_configuration
# * https://pve.proxmox.com/wiki/Firewall
# * https://pve.proxmox.com/pve-docs/chapter-pmxcfs.html
# * https://forum.proxmox.com/threads/unable-to-modify-anything-under-etc-pve.10284/
# * https://r-pufky.github.io/docs/virtualization/hypervisors/pve/index.html#firewall
# * https://r-pufky.github.io/docs/virtualization/hypervisors/pve/index.html#ports

- name: 'Host firewall | set cluster node'
  ansible.builtin.set_fact:
    _pve_cluster_firewall_host: '{{ host.split(".")[0] }}'

- name: 'Host firewall | {{ _pve_cluster_firewall_host }} check for changes' # noqa name[template] risky-file-permissions pmxcfs managed
  ansible.builtin.copy:
    src: 'host.fw'
    dest: '/etc/pve/nodes/{{ _pve_cluster_firewall_host }}/host.fw'
    force: true
  check_mode: true
  register: _pve_node_firewall_check

- name: 'Host firewall | {{ _pve_cluster_firewall_host }} stage changes' # noqa name[template] no-handler conditional
  when: _pve_node_firewall_check.changed
  ansible.builtin.copy:
    src: 'host.fw'
    dest: '/tmp/host.fw'
    owner: 'root'
    group: 'www-data'
    mode: '0640'
    force: true

- name: 'Host firewall | {{ _pve_cluster_firewall_host }} apply changes to pmxcfs' # noqa name[template] no-handler execute immediately
  when: _pve_node_firewall_check.changed
  ansible.builtin.command: 'mv -f /tmp/host.fw /etc/pve/nodes/{{ _pve_cluster_firewall_host }}/host.fw'
  changed_when: false
